# Generated by Django 4.1.6 on 2023-02-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
