# Generated by Django 4.1.7 on 2023-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_one', models.URLField()),
                ('short_one', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
    ]
