# Generated by Django 4.1.7 on 2023-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortener',
            fields=[
                ('code', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
