# Generated by Django 4.1.7 on 2023-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='make_short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.URLField()),
                ('url_short', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': '',
            },
        ),
    ]
