# Generated by Django 4.1.4 on 2023-02-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_date_completed_list_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='list',
            name='date_created',
        ),
    ]
