# Generated by Django 4.1.4 on 2023-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_list_date_completed_list_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_completed',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
