# Generated by Django 4.1.4 on 2023-02-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_list_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='list',
            name='date_created',
        ),
    ]
