# Generated by Django 4.1.4 on 2023-02-21 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_list_date_completed_remove_list_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date_completed',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
