# Generated by Django 4.1.7 on 2023-03-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('url_long', models.URLField()),
                ('random_code', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
