# Generated by Django 4.1.7 on 2023-02-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_shortener_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='new_URL',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
