# Generated by Django 4.1.7 on 2023-03-01 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylister',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocerylister',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
