# Generated by Django 4.1.7 on 2023-03-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='following',
        ),
    ]
