import random
import json

'''
Let's define our variables
We can add to this as along the way, and some variables will be defined on the fly
But this is where all pre-variables should go
'''

inventory = []
daytime = 12
what_do = ['Travel', 'Explore', 'Scavenge', 'Fortify', 'Rest']
where_to = [] # we need to define our grid size...COULD GRID SIZE BE PART OF DIFFICULTY LEVEL?
player_HP = 10
base_defenses = 5
day_counter = 0



print('''The world has ended...
\n...
\n...
\n...


In the wake of the COVID-19 pandemic...
\nThe people of the United States had grown tired of living their lives in fear of the invisible...
\n
\n...
\n...
Some other stuff that references... 
\nthe fractured nature of our current reality...
\nand explains the spread of the zombie virus...ZMB-13
\n...
\n...
Some descirption of...
\nyour escape from whatever city you escaped from...
\nand how you made your way to the base in the woods
\n...
\n...
The Old World is dead...
Welcome to the New World, Zed-bait...
''')

while True:

    print(f"It is Day {day_counter}")
    action = input("What would you like to do?").title()

    if action not in what_do:
        print("That is not an option")

    elif 