# Generated by Django 4.1.6 on 2023-02-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='booleanFlag',
            field=models.BooleanField(default=False),
        ),
    ]
