# Generated by Django 4.1.7 on 2023-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('created_date', models.IntegerField()),
                ('completed_date', models.IntegerField()),
                ('complete', models.CharField(max_length=3)),
                ('incomplete', models.CharField(max_length=3)),
            ],
        ),
    ]
