# Generated by Django 4.1.6 on 2023-02-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='text',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
