# Generated by Django 4.1.6 on 2023-03-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_imgmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='my_image',
            field=models.ImageField(upload_to='uploaded_files/images/'),
        ),
    ]
