# Generated by Django 4.1.6 on 2023-03-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0004_alter_imgmodel_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='my_image',
            field=models.ImageField(upload_to='uploaded_images/images/'),
        ),
    ]
