# Generated by Django 4.1.6 on 2023-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='itemDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
