# Generated by Django 4.1.7 on 2023-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishspeciesmodel',
            name='fish_location',
        ),
        migrations.RemoveField(
            model_name='fishspeciesmodel',
            name='fish_taste',
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishSfat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fish_habitat',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishcalories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishcarbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishcholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishenvironment',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishfarming',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishfat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishfiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishhealth',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishphoto',
            field=models.ImageField(default=0, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishprotein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishrate',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishsodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishtaste',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='fishspeciesmodel',
            name='fishtexture',
            field=models.TextField(default=0),
        ),
    ]
