# Generated by Django 4.1.6 on 2023-02-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='long_url',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
