# Generated by Django 4.1.6 on 2023-02-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shorturl_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='host_header',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
